<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridView.aspx.cs" Inherits="ASP_Tutorial.GridView" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Grid View Methods Exercise</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="Id" DataSourceID="SqlDataSource1" ForeColor="Black" GridLines="Vertical" ShowFooter="True">
                <AlternatingRowStyle BackColor="#CCCCCC" />
                <Columns>
                    <%--ID Template--%>
                    <asp:TemplateField HeaderText="Id" InsertVisible="False" SortExpression="Id">
                        <EditItemTemplate>
                            <asp:Label ID="Lbl_Id_Edit" runat="server" Text='<%# Eval("Id") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Lbl_Id" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:LinkButton OnClick="Lnk_Insert_Click" ID="Lnk_Insert" ValidationGroup="Insert" runat="server">Insert</asp:LinkButton>
                        </FooterTemplate>
                    </asp:TemplateField>
                    <%--Name Template--%>
                    <asp:TemplateField HeaderText="Name" SortExpression="name">
                        <EditItemTemplate>
                            <asp:TextBox ID="Txt_Name" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ID="EditNameValidator" runat="server" ErrorMessage="Please enter a name" Display="Dynamic" Text="*" ControlToValidate="Txt_Name" SetFocusOnError="True" ForeColor="red"></asp:RequiredFieldValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Lbl_Name" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="Txt_Name_Insert" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="InsertNameValidator" runat="server" ErrorMessage="Please enter a name" Display="Dynamic" Text="*" ControlToValidate="Txt_Name_Insert" SetFocusOnError="True" ValidationGroup="Insert" ForeColor="Red"></asp:RequiredFieldValidator>
                        </FooterTemplate>
                    </asp:TemplateField>
                    <%--Gender Template--%>
                    <asp:TemplateField HeaderText="Gender" SortExpression="gender">
                        <EditItemTemplate>
                            <asp:DropDownList ID="Drp_Gender_Edit" runat="server" Text='<%# Bind("gender") %>'>
                                <asp:ListItem>Select Gender</asp:ListItem>
                                <asp:ListItem>Male</asp:ListItem>
                                <asp:ListItem>Female</asp:ListItem>
                            </asp:DropDownList>
                            <asp:RequiredFieldValidator ID="EditGenderValidator" runat="server" InitialValue="Select Gender" ErrorMessage="Please enter a gender" Display="Dynamic" Text="*" ControlToValidate="Drp_Gender_Edit" SetFocusOnError="True" ForeColor="Red"></asp:RequiredFieldValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("gender") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:DropDownList ID="Drp_Gender_Insert" runat="server">
                                <asp:ListItem>Select Gender</asp:ListItem>
                                <asp:ListItem>Male</asp:ListItem>
                                <asp:ListItem>Female</asp:ListItem>
                            </asp:DropDownList>
                            <asp:RequiredFieldValidator ID="InsertGenderValidator" runat="server" InitialValue="Select Gender" ErrorMessage="Please enter a gender" Display="Dynamic" Text="*" ControlToValidate="Drp_Gender_Insert" SetFocusOnError="True" ValidationGroup="Insert" ForeColor="Red"></asp:RequiredFieldValidator>
                        </FooterTemplate>
                    </asp:TemplateField>
                    <%--Class Template--%>
                    <asp:TemplateField HeaderText="Class" SortExpression="class">
                        <EditItemTemplate>
                            <asp:TextBox ID="Txt_Class_Edit" runat="server" Text='<%# Bind("class") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ID="EditClassValidator" runat="server" ErrorMessage="Please enter a class" Display="Dynamic" Text="*" ControlToValidate="Txt_Class_Edit" SetFocusOnError="True" ForeColor="Red"></asp:RequiredFieldValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Lbl_Class" runat="server" Text='<%# Bind("class") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="Txt_Class_Insert" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="InsertClassValidator" runat="server" ErrorMessage="Please enter a class" Display="Dynamic" Text="*" ControlToValidate="Txt_Class_Insert" SetFocusOnError="True" ValidationGroup="Insert" ForeColor="Red"></asp:RequiredFieldValidator>
                        </FooterTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>

             <asp:ValidationSummary ID="InsertValidationSummary" runat="server" BackColor="#CCCCCC" DisplayMode="BulletList" ValidationGroup="Insert" ForeColor="Red" />
            <asp:ValidationSummary ID="EditValidationSummary" runat="server" BackColor="#CCCCCC" DisplayMode="BulletList" ForeColor="Red" />
           

            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:dbcs %>" DeleteCommand="DELETE FROM [Student] WHERE [Id] = @Id" InsertCommand="INSERT INTO [Student] ([name], [gender], [class]) VALUES (@name, @gender, @class)" SelectCommand="SELECT * FROM [Student]" UpdateCommand="UPDATE [Student] SET [name] = @name, [gender] = @gender, [class] = @class WHERE [Id] = @Id">
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="gender" Type="String" />
                    <asp:Parameter Name="class" Type="Int32" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="gender" Type="String" />
                    <asp:Parameter Name="class" Type="Int32" />
                    <asp:Parameter Name="Id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
